name: Test

on:
  push:
    branches:
      - master
# In the calling repository's .github/workflows/calling-workflow.yml
jobs:
  call-reusable-workflow:
    uses: amstokely/env_check/.github/workflows/check_env.yml@master
    with:
      other_repo: "owner/env_check_test"
      file_path: "log.txt"
      access_token: ${{ secrets.ACCESS_TOKEN }}
