name: test

on:
  push:
    branches:
      - master
# In the calling repository's .github/workflows/calling-workflow.yml
jobs:
  call-reusable-workflow:
    uses: amstokely/env_check/.github/workflows/env_check.yml@master
    with:
      file_path: log.txt
